#!/bin/bash
if [ "$1" = "run" ]; then
    qmake
    make
    ./steganoZPR
elif [ "$1" = "test" ]; then
    cd SteganoTests
    qmake
    make
    ./SteganoTests  
elif [ "$1" = "clean" ]; then
    cd SteganoTests
    make clean &> /dev/null
    rm -f Makefile SteganoTests
    cd ..
    make clean &> /dev/null
    rm -f Makefile steganoZPR
    rm -f -r doxygen_doc/
elif [ "$1" = "docs" ]; then
    doxygen doxygen_conf
else
    qmake
    make
fi
