#!/bin/bash
if [ "$1" = "run" ]; then
    qmake
    make
    ./steganoZPR
elif [ "$1" = "test" ]; then
    cd SteganoTests
    qmake
    make
    ./SteganoTests
    echo "End of tests."
elif [ "$1" = "clean" ]; then
    cd SteganoTests
    make clean &> /dev/null
    rm -f Makefile SteganoTests
    cd ..
    make clean &> /dev/null
    rm -f Makefile steganoZPR
    rm -f -r doxygen_doc/
    echo "Cleaning finished."
elif [ "$1" = "docs" ]; then
    doxygen doxygen_conf
    echo "Doxygen docs generated to folder doxygen_doc/"
else
    qmake
    make
fi
